services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mount code for development, remove for production
    # command: python manage.py runserver 0.0.0.0:8000 # Already in Dockerfile CMD
    depends_on:
      - db # Example if a database service is added
    environment:
      - DJANGO_SETTINGS_MODULE=backend_project.settings
      # Add other environment variables as needed
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Or 3000:80 if Vite dev server is exposed on 3000 and Nginx proxies
    volumes:
      - ./frontend/src:/app/src # Mount src for development, adjust as needed
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  db: # Example PostgreSQL service, adjust as needed or remove if using SQLite
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    ports:
      - "5432:5432"

volumes:
  postgres_data: # Defines the named volume for data persistence