# Generated by Django 5.1.5 on 2025-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('is_developer', models.BooleanField(default=False)),
            ],
        ),
    ]
