# Generated by Django 5.1.6 on 2025-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallets',
            field=models.TextField(default=''),
        ),
    ]
