# Generated by Django 5.1.6 on 2025-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
