# Generated by Django 5.1.6 on 2025-03-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS Content Identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_metadata',
            field=models.JSONField(blank=True, help_text='IPFS 元数据，包含文件大小、上传时间等信息', null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_status',
            field=models.CharField(choices=[('pending', '待上传'), ('uploaded', '已上传'), ('failed', '上传失败')], default='pending', help_text='IPFS 上传状态', max_length=20),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='IPFS 上传时间', null=True),
        ),
    ]
