# Generated by Django 5.1.6 on 2025-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0002_botmanagement_ipfs_cid_botmanagement_ipfs_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmanagement',
            old_name='ipfs_cid',
            new_name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='ipfs_metadata',
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_url',
            field=models.URLField(blank=True, help_text='IPFS 文件访问URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='is_ipfs_locked',
            field=models.BooleanField(default=False, help_text='是否已锁定IPFS上传'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待上传'), ('uploaded', '已上传'), ('failed', '上传失败')], default='draft', help_text='IPFS 上传状态', max_length=20),
        ),
    ]
