# Generated by Django 5.1.6 on 2025-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0003_rename_ipfs_cid_botmanagement_ipfs_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmanagement',
            name='contract_address',
            field=models.CharField(blank=True, help_text='机器人在智能合约中的地址', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='上架时间', null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='上架交易的哈希值', max_length=66, null=True),
        ),
    ]
