# Generated by Django 5.1.6 on 2025-03-29 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0004_botmanagement_contract_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmanagement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='bots/'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='bots/'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='bots/'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_status',
            field=models.CharField(choices=[('pending', '待上传'), ('uploaded', '已上传'), ('failed', '上传失败')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='is_ipfs_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='trial_time',
            field=models.IntegerField(help_text='试用时间（天）'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
