# Generated by Django 5.1.6 on 2025-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0005_alter_botmanagement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmanagement',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='ipfs_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='ipfs_url',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='botmanagement',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='bot_images/'),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='ipfs_status',
            field=models.CharField(choices=[('pending', '待上传'), ('uploading', '上传中'), ('uploaded', '已上传'), ('failed', '上传失败')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='botmanagement',
            name='trial_time',
            field=models.IntegerField(default=0),
        ),
    ]
