# Generated by Django 5.1.6 on 2025-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0006_remove_botmanagement_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmanagement',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='bot_images/'),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='bot_images/'),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='ipfs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmanagement',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
