# Generated by Django 5.1.6 on 2025-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanagement', '0007_botmanagement_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmanagement',
            name='contract_bot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
