# Generated by Django 5.1.6 on 2025-05-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botmanagement', '0008_botmanagement_contract_bot_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETH-USDT', max_length=10)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('subscribed', 'Subscribed')], default='pending', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('trial_period_days', models.IntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanagement.botmanagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
