# Generated by Django 5.1.6 on 2025-05-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='trial_period_days',
            new_name='trial_period_hours',
        ),
    ]
